### PR TITLE
add apple silicon support

### PR DESCRIPTION
**Pull request by JonnyBurger**
This builds on M1

### CODE REVIEW

**Review by gsmachado — CHANGES_REQUESTED** [review]
Instead, use `golang:1.16-alpine3.13` image tag as `FROM` -- and not the raw `alpine:3.13` with an additional (unnecessary) `apk add go` command.

💪

**Comment by JonnyBurger** [comment]
Nevermind, it works now just without changes. Weird.

I did not want to use a specific alpine version, I wanted to install Go for the arm64 architecture which I thought did not come with the image, so I wanted to fetch it from `apk`.

But it works now just like that, so closing.

**Comment by gsmachado** [comment]
I love when issues get resolved, magically, by themselves. 👍  💯  ❤️  😅

**Comment by JonnyBurger** [comment]
Indeed! 😅 thanks for reviewing, hope to see you soon!

**Pull request closed without merging**
